### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by goibon** [goibon/spooky-meter#4]
To encourage users to use the site as a standalone app a nice icon would really help seal so it doesn't just use a screenshot of the site.

**Comment by goibon** [comment]
@jbeguna04 is this something you could be interested in helping out with? 😃

**Comment by jbeguna04** [comment]
Sure Im available right now. Just please give me more information about the project. Or Ideas about the logo. Thank you in advance ;)

**Comment by goibon** [comment]
Cool! Well the concept is quite simple, there is a spooky meter that shows one of five different values describing how spooky it is.
You can try it yourself at http://spoopy.tk/
For now I've just been using a ghost emoji as favicon, but I think since the spooky levels are mainly focused on how close you are to skeletons the icon should be a skeleton or skull of some sort.
I'd love to hear your ideas on this 😄
